// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Recognizes the user's emotion from their facial expression.
 *
 * - recognizeUserEmotion - A function that handles the emotion recognition process.
 * - RecognizeUserEmotionInput - The input type for the recognizeUserEmotion function.
 * - RecognizeUserEmotionOutput - The return type for the recognizeUserEmotion function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecognizeUserEmotionInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of the user's face, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type RecognizeUserEmotionInput = z.infer<typeof RecognizeUserEmotionInputSchema>;

const RecognizeUserEmotionOutputSchema = z.object({
  emotion: z
    .string()
    .describe('The recognized emotion of the user (e.g., happy, sad, angry, neutral).'),
  confidence: z
    .number()
    .describe('The confidence level of the emotion recognition (0 to 1).'),
});
export type RecognizeUserEmotionOutput = z.infer<typeof RecognizeUserEmotionOutputSchema>;

export async function recognizeUserEmotion(
  input: RecognizeUserEmotionInput
): Promise<RecognizeUserEmotionOutput> {
  return recognizeUserEmotionFlow(input);
}

const recognizeUserEmotionPrompt = ai.definePrompt({
  name: 'recognizeUserEmotionPrompt',
  input: {schema: RecognizeUserEmotionInputSchema},
  output: {schema: RecognizeUserEmotionOutputSchema},
  prompt: `You are an AI emotion recognition expert. Analyze the facial expression in the provided image and determine the user's emotion.

  Respond with the recognized emotion and the confidence level (0 to 1).

  Photo: {{media url=photoDataUri}}
  `,
});

const recognizeUserEmotionFlow = ai.defineFlow(
  {
    name: 'recognizeUserEmotionFlow',
    inputSchema: RecognizeUserEmotionInputSchema,
    outputSchema: RecognizeUserEmotionOutputSchema,
  },
  async input => {
    const {output} = await recognizeUserEmotionPrompt(input);
    return output!;
  }
);
